# [program:XXXXXXXX]
# process_name=%(program_name)s_%(process_num)02d
# command=php /XXXX/think queue:listen --queue=takeout-cancel
# directory=/data0/htdocs/api-prod-shop.jingxishenghuo1688.com         
# numprocs=1
# autostart=true
# autorestart=true
# user=www-data
# redirect_stderr=true
# stdout_logfile=/XXXX/queue-shop-takeout-cancel.log
# stderr_logfile=/XXXX/queue-shop-takeout-cancel_err.log