apiVersion: v1
kind: Service
metadata:
  name: {{ include "st.fullname" . }}-hs
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "st.fullname" . }}
    {{- include "st.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app: {{ include "st.fullname" . }}
  ports:
    - name: hazelcast
      port: {{ .Values.service.hazelcastPort }}
      targetPort: hazelcast
    - name: engine-api
      port: {{ .Values.service.engineApiPort }}
      targetPort: engine-api
