{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "st.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "st.fullname" . }}
    {{- include "st.labels" . | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "st.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: engine-api
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
