# Overlay values for DS chart deployment
timezone: "Asia/Shanghai"

image:
  registry: "192.168.5.103:5000"
  tag: 3.1.7
  pullPolicy: "IfNotPresent"
  pullSecret: ""
  master: apache/dolphinscheduler-master
  worker: ds-worker-custom
  api: apache/dolphinscheduler-api
  alert: apache/dolphinscheduler-alert-server
  tools: apache/dolphinscheduler-tools

externalDatabase:
  type: "postgresql"
  host: "pg-ha-rw.postgres.svc"
  port: "5432"
  username: "postgres"
  password: "postgres123"
  database: "dolphinscheduler"
  params: "characterEncoding=utf8"

zookeeper:
  quorum: "ds-zookeeper.dolphinscheduler.svc:2181"

master:
  replicas: 1
  resources:
    limits:
      memory: "1Gi"
  persistence:
    enabled: false

worker:
  replicas: 1
  resources:
    limits:
      memory: "2Gi"
  persistence:
    enabled: true
    data:
      enabled: false
    logs:
      enabled: true
      size: "10Gi"
      storageClass: "nfs-client"

api:
  replicas: 1
  resources:
    limits:
      memory: "1Gi"
  service:
    type: "ClusterIP"
  persistence:
    enabled: false

alert:
  replicas: 1
  resources:
    limits:
      memory: "512Mi"
  persistence:
    enabled: false

serviceMonitor:
  enabled: true
  interval: 30s
  labels:
    release: kube-prometheus-stack
