apiVersion: v2
name: redis-operator
description: OT-Container-KIT Redis Operator (v0.9.0) — K8s 1.19 兼容版
type: application
version: 0.9.0
appVersion: "0.9.0"
home: https://github.com/OT-CONTAINER-KIT/redis-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
maintainers:
  - name: jory
keywords:
  - redis
  - operator
  - redis-operator
