apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: victoria-metrics-k8s-stack
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.85.2
    releaseName: victoria-stack
    namespace: monitoring
    valuesFile: values.yaml

resources:
  - rules
  - resourcequota.yaml
