apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: operator
    repo: https://operator.min.io/
    version: 7.1.1
    releaseName: minio-operator
    namespace: operators
    valuesFile: values.yaml
    includeCRDs: true
