apiVersion: v2
name: redis-operator
description: OT-Container-KIT Redis Operator v0.25.0
type: application
version: 0.25.0
appVersion: "0.25.0"
home: https://github.com/OT-CONTAINER-KIT/redis-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
maintainers:
  - name: jory
keywords:
  - redis
  - operator
