---
# defaults file for roles/docker
# Docker配置
docker_version: "latest"   # Docker版本
docker_mirror: "https://mirrors.tuna.tsinghua.edu.cn/docker-ce"  # 清华源
docker_users: []   # 添加到docker组的用户

# Docker守护进程配置
docker_daemon_config:
  log-driver: "json-file"
  log-opts:
    max-size: "10m"
    max-file: "3"
  storage-driver: "overlay2"
  insecure-registries: []                  # 私有仓库
  registry_mirrors:                        # 镜像加速器
  - "https://192.168.1.211:20443"
  - "https://docker.xuanyuan.me"
  - "https://docker.1ms.run"


# 服务管理
docker_service_state: started              # 服务状态
docker_service_enabled: true               # 是否开机启动




