apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: victoria-logs-collector
    repo: https://victoriametrics.github.io/helm-charts/
    version: 0.3.6
    releaseName: victoria-logs-collector
    namespace: victorialogs
    valuesFile: values.yaml
