user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for"';
    access_log  /var/log/nginx/access.log  main;
    client_header_timeout 5s;
    client_body_timeout 5s;
    send_timeout 10s;
    sendfile        on;
    #tcp_nopush     on;
    gzip  on;
    keepalive_timeout  65; 
    server_tokens off;  # no display nginx version;
    client_max_body_size 1000m; # http binary upload max size

    limit_conn_zone $binary_remote_addr zone=addr:10m;
    limit_req_zone $binary_remote_addr zone=req_limit_per_ip:10m rate=5r/s;

    include /etc/nginx/conf.d/*.conf;
    
}

# stream {
# }
