apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ds.name" . }}-configs
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}-configs
data:
  common_properties: |-
{{ tpl (.Files.Get "conf/common.properties") . | indent 4 }}
