apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ds.name" . }}-common
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}-common
data:
  {{- range $key, $value := .Values.common.configmap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
