{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ds.name" . }}
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "ingress") | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: "{{ .Values.ingress.host }}"
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          pathType: Prefix
          backend:
            service:
              name: {{ include "ds.name" . }}-api
              port:
                name: api-port
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
