apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ds.name" . }}
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ds.name" . }}
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ds.name" . }}
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ds.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ds.name" . }}
    namespace: {{ .Release.Namespace }}
