apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ds.name" . }}-externaldb
  labels:
    {{- include "ds.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "ds.name" . }}-externaldb
type: Opaque
data:
  database-password: {{ .Values.externalDatabase.password | b64enc | quote }}
