version: "3.7"

services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    #user: root
    #privileged: true     #设置容器权限为root
    #设置网络模式为 host 模式
    #network_mode: host  
    #这个与上面的二选一，网络模式为 bridge 模式
    networks:
      - env-dev
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      TZ: Aisa/Shanghai
      MINIO_ACCESS_KEY: admin       # 访问密钥
      MINIO_SECRET_KEY: admin123456 # 密码长度不能小于8位
    volumes:
      # 让容器使用和服务器同样的时间设置
      - /etc/localtime:/etc/localtime:ro
      - /data/env-docker-data/minio/data:/data:rw
      - ./conf:/root/.minio:rw
    command:
        #console-address是运维的可视化界面地址。address是minio的服务地址
      server /data  --console-address ":9000"  --address ":9001"

networks:
  env-dev:
    external: true

