version: "3.7"
services:
  oracle11g:
    image: registry.cn-hangzhou.aliyuncs.com/akaiot/oracle_11g:latest
    container_name: oracle11g
    restart: always
    networks:
      - env-dev
    ports:
      - '1521:1521'
    environment:
      - TZ=Aisa/Shanghai
    volumes:
      - ./oracle_data/oradata/:/home/oracle/app/oracle/oradata
      - ./oracle_data/admin/:/home/oracle/app/oracle/admin
      - ./oracle_data/flash_recovery_area/:/home/oracle/app/oracle/flash_recovery_area
      - ./oracle_data/cfgtoollogs/:/home/oracle/app/oracle/cfgtoollogs
      - ./oracle_data/checkpoints/:/home/oracle/app/oracle/checkpoints
      - ./oracle_data/diag/:/home/oracle/app/oracle/diag
      - ./oracle_data/oradiag_oracle/:/home/oracle/app/oracle/oradiag_oracle

networks:
  env-dev:
    external: true
