---
apiVersion: v1
kind: Service
metadata:
  name: rfrm-redisfailover-ha
  namespace: redis-spotahome-v111
  labels:
    app: redis-failover
    redis-failover: redisfailover-ha
    redisfailovers: redisfailover-ha
spec:
  ports:
    - port: 6379
      name: redis
      targetPort: 6379
      nodePort: 30207
  selector:
    redisfailovers: redisfailover-ha
    redisfailovers-role: master
  type: NodePort