[k3s_server]
k3s-server-1 ansible_host=192.168.5.107

[k3s_agent]
k3s-agent-1 ansible_host=192.168.5.108
k3s-agent-2 ansible_host=192.168.5.110
k3s-agent-3 ansible_host=192.168.5.111


[k3s_cluster:children]
k3s_server
k3s_agent

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519

# 时区
timezone=Asia/Shanghai

# --- linux ---
# 日志保留
log_retention_days=7
journald_max_size=500M

# --- docker ---
# 镜像源 (私有 registry group)
# Docker 数据目录
docker_data_root=/var/lib/docker
# docker 镜像源
docker_registry_mirror=http://192.168.5.103:5000

# ---- K3s ----
# 版本
k3s_version=v1.31.5-k3s1
# 数据目录
# 推荐: /mnt/data_1/k3s（独立数据盘挂载点），当前 /opt/k3s_data 是临时路径
k3s_data_dir=/opt/k3s_data
# Token: openssl rand -base64 32 | tr -d '/+=' | cut -c1-48
k3s_token=k3s-ha-40yhw4NU19XyWZC5naohc5tSoPMC6wKx3nB34zXo624
