[k3s_server]
k3s-server-1 ansible_host=192.168.5.123

[k3s_agent]
k3s-agent-1 ansible_host=192.168.5.124
k3s-agent-2 ansible_host=192.168.5.125


[k3s_cluster:children]
k3s_server
k3s_agent

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=~/.ssh/id_ed25519

# --- linux ---
# 时区
timezone=Asia/Shanghai
# 日志保留
log_retention_days=7
journald_max_size=500M
# keepalived
keepalived_vip=192.168.5.254/24

# --- docker ---
# Docker 数据目录
docker_data_root=/var/lib/docker
# Docker 日志（限制单文件大小和保留数）
docker_log_max_size=100m
docker_log_max_file=3
# docker 镜像源（JSON 数组格式，支持多个）
docker_registry_mirror=["http://192.168.5.103:5000"]

# ---- K3s ----
# 版本
k3s_version=v1.31.5-k3s1
# 数据目录
# 推荐: /mnt/data_1/k3s（独立数据盘挂载点），当前 /opt/k3s_data 是临时路径
k3s_data_dir=/opt/k3s_data
# Token: openssl rand -base64 32 | tr -d '/+=' | cut -c1-48
k3s_token=k3s-ha-40yhw4NU19XyWZC5naohc5tSoPMC6wKx3nB34zXo624
# ---- TLS SAN 额外条目 ----
# 自动注入：所有 server 节点 IP + hostname，此处只定义额外需要的域名/IP
k3s_tls_san=["k3s-api.internal","k3s-server.internal","192.168.5.254"]

# ---- MetalLB 地址池 192.168.5.252-192.168.5.253----
; metallb_ip_range=192.168.5.252-192.168.5.253
