apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kdebug.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kdebug.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kdebug.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kdebug.selectorLabels" . | nindent 8 }}
    spec:
      terminationGracePeriodSeconds: 30

      {{- if .Values.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "kdebug.selectorLabels" . | nindent 20 }}
                topologyKey: {{ .Values.podAntiAffinity.topologyKey }}
      {{- end }}

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: http
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VERSION
              value: {{ .Values.image.tag | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            failureThreshold: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 3
            periodSeconds: 5
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 5"]
