version: "3.7"

services:
  dragonflyDB:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonflyDB
    restart: always
    # network_mode: host
    networks:
      - net-shared
    ports:
     - '6377:6379'
    volumes:
      - ./data:/data
    ulimits:
      #rtprio: 95
      memlock: -1

networks:
  net-shared:
    external: true
