apiVersion: v1
kind: Service
metadata:
  name: ds-zookeeper
  namespace: dolphinscheduler
  labels:
    app: ds-zookeeper
spec:
  clusterIP: None
  selector:
    app: ds-zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: 2181
    - name: follower
      port: 2888
      targetPort: 2888
    - name: election
      port: 3888
      targetPort: 3888
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ds-zookeeper
  namespace: dolphinscheduler
spec:
  serviceName: ds-zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: ds-zookeeper
  template:
    metadata:
      labels:
        app: ds-zookeeper
    spec:
      containers:
        - name: zookeeper
          image: 192.168.5.103:5000/library/zookeeper:3.8.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: follower
            - containerPort: 3888
              name: election
          livenessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 2181
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            limits:
              memory: "1Gi"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: nfs-client
        resources:
          requests:
            storage: 8Gi
