---
# Secret — 认证密码
apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: redis-spotahome
type: Opaque
stringData:
  password: "redis@czw"
---
# 外部访问 Service — NodePort 30201 暴露 Redis master
apiVersion: v1
kind: Service
metadata:
  name: rfrm-redisfailover-ha-external
  namespace: redis-spotahome
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      nodePort: 30206
  selector:
    app.kubernetes.io/component: redis
    app.kubernetes.io/name: redisfailover-ha
    app.kubernetes.io/part-of: redis-failover
    redisfailovers-role: master