apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kite
    repo: oci://ghcr.io/kite-org/charts
    version: 0.12.3
    releaseName: kite
    namespace: kite
    valuesFile: values.yaml

resources:
  - service.yaml
