apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: apecloud-mysql
  namespace: mysql
spec:
  terminationPolicy: Delete
  clusterDef: apecloud-mysql
  topology: apecloud-mysql
  componentSpecs:
    - name: mysql
      serviceVersion: "8.0.30"
      disableExporter: false
      replicas: 3
      resources:
        limits:
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            # storageClassName: nfs-client
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
