apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-operator.name" . }}
  namespace: {{ include "redis-operator.namespace" . }}
  labels: {{- include "redis-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      control-plane: {{ include "redis-operator.name" . }}
  replicas: 1
  template:
    metadata:
      labels: {{- include "redis-operator.labels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: 65532
      containers:
      - command: ["/manager"]
        args: ["--leader-elect"]
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet: { path: /healthz, port: 8081 }
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet: { path: /readyz, port: 8081 }
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{ toYaml .Values.resources | nindent 10 }}
      terminationGracePeriodSeconds: 10
      serviceAccount: {{ include "redis-operator.name" . }}
      serviceAccountName: {{ include "redis-operator.name" . }}
