{{- if .Values.sentinel.enabled }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: {{ .Values.sentinel.name }}
spec:
  clusterSize: {{ .Values.sentinel.clusterSize }}
  podSecurityContext:
    runAsUser: {{ .Values.sentinel.podSecurityContext.runAsUser }}
    fsGroup: {{ .Values.sentinel.podSecurityContext.fsGroup }}
  redisSentinelConfig:
    redisReplicationName: {{ .Values.sentinel.replicationName }}
  kubernetesConfig:
    image: "{{ $.Values.redisSentinelImage.repository }}:{{ $.Values.redisSentinelImage.tag }}"
    imagePullPolicy: {{ $.Values.redisSentinelImage.pullPolicy }}
    resources:
      requests:
        cpu: {{ .Values.sentinel.resources.requests.cpu }}
        memory: {{ .Values.sentinel.resources.requests.memory }}
      limits:
        memory: {{ .Values.sentinel.resources.limits.memory }}
  redisExporter:
    enabled: {{ .Values.sentinel.exporter.enabled }}
    image: "{{ $.Values.redisExporterImage.repository }}:{{ $.Values.redisExporterImage.tag }}"
    imagePullPolicy: {{ $.Values.redisExporterImage.pullPolicy }}
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
  pdb:
    enabled: {{ .Values.sentinel.pdb.enabled }}
    minAvailable: {{ .Values.sentinel.pdb.minAvailable }}
{{- end }}
