{{- if .Values.cluster.enabled }}
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: {{ .Values.cluster.name }}
spec:
  clusterSize: {{ .Values.cluster.clusterSize }}
  clusterVersion: v7
  persistenceEnabled: true
  podSecurityContext:
    runAsUser: {{ .Values.cluster.podSecurityContext.runAsUser }}
    fsGroup: {{ .Values.cluster.podSecurityContext.fsGroup }}
  kubernetesConfig:
    image: "{{ $.Values.redisImage.repository }}:{{ $.Values.redisImage.tag }}"
    imagePullPolicy: {{ $.Values.redisImage.pullPolicy }}
    resources:
      requests:
        cpu: {{ .Values.cluster.resources.requests.cpu }}
        memory: {{ .Values.cluster.resources.requests.memory }}
      limits:
        memory: {{ .Values.cluster.resources.limits.memory }}
  redisExporter:
    enabled: {{ .Values.cluster.exporter.enabled }}
    image: "{{ $.Values.redisExporterImage.repository }}:{{ $.Values.redisExporterImage.tag }}"
    imagePullPolicy: {{ $.Values.redisExporterImage.pullPolicy }}
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
  redisLeader:
    replicas: 1
  redisFollower:
    replicas: 1
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.cluster.storage }}
    nodeConfVolume: true
    nodeConfVolumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  pdb:
    enabled: {{ .Values.cluster.pdb.enabled }}
    minAvailable: {{ .Values.cluster.pdb.minAvailable }}
{{- end }}
