apiVersion: v1
kind: Service
metadata:
  name: demo-go-tiny-nodeport
  labels:
    app: demo-go-tiny
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30301
      protocol: TCP
  selector:
    app: demo-go-tiny