services:
  acmesh:
    container_name: acmesh
    image: neilpang/acme.sh
    restart: always
    environment:
      - ACME_ACCOUNT_EMAIL=${ACME_ACCOUNT_EMAIL}
      - Tencent_SecretId=${Tencent_SecretId}
      - Tencent_SecretKey=${Tencent_SecretKey}
    volumes:
      - ./out:/acme.sh
      - ./nginx-ssl/:/nginx-ssl
    stdin_open: true
    tty: true
    network_mode: host
    command: daemon
