# 全局通用变量
USE_DOCKER: true
DOCKER_IMAGE_GIT: "alpine/git"
DOCKER_IMAGE_PHP: "php:7.4-fpm"
DOCKER_IMAGE_NODE: "node:16-alpine"

SOURCECODE_ROOT: "/data/sourcecode"
BUILD_ROOT: "/data/deploycode"
DEPLOY_ROOT: "/data/www"

PATH_MODE: "domain"   # domain | project

DEPLOY_STRATEGY: "rsync"
DEPLOY_EXCLUDES:
  - "node_modules"
  - ".git"
  - "vendor"

RSYNC_EXCLUDE_DEFAULT:
  - ".git"
  - ".env"