# 全局通用变量
USE_DOCKER: true
DOCKER_IMAGE_GIT: "alpine/git"
PHP_VERSION: "7.4"
DOCKER_IMAGE_PHP: "phpfpm:{{ PHP_VERSION }}"
NODE_VERSION: "20"
DOCKER_IMAGE_NODE: "node: {{ NODE_VERSION }}"

DEPLOY_ENV: "test"
PROJECT_TYPE: "" # 项目类型，如 php, node, h5

SOURCECODE_ROOT_DIR: "/data/sourcecode"
ARTIFACT_ROOT_DIR: "/data/artifact"
BUILD_SUB_DIR: "" # 构建子目录 (如 admin，默认为空即根目录, 用于支持不规范的仓库结构)
DEPLOY_ROOT_DIR: "/data/deploy"
PROJECT_PATH: "xxx.example.local" # 项目域名部署路径


TARGET_HOSTS: ""
