# 项目默认变量（可从 GIT_REPO 自动解析 project_path，这里留空由 common role 推导）
GIT_REPO: "https://codeup.aliyun.com/63d89ae93a/ims/ims-management.git"
GIT_BRANCH: "main"
GIT_COMMIT_ID: ""

# PHP
php_build_enabled: true
php_version: "7.4"
php_build_command: >-
  composer config audit.block-insecure false &&
  composer config -g process-timeout 600 &&
  composer install --optimize-autoloader
php_build_excludes: []

# Node.js
node_build_enabled: false
node_version: "16"
node_build_command: "npm i && npm run build:prod"

# H5
h5_enabled: false
h5_zip_need_unzip: true
h5_zip_file_path: "dist/dist.zip"
h5_zip_unique_index_file: "index.html"