apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sre-lab
  namespace: argocd
spec:
  description: SRE Lab project
  sourceRepos:
    - 'https://github.com/jory-callan/sre-lab'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
