# 检查必备变量
- name: 开始 构建 操作, node , 检查必备变量
  assert:
    that:
      - item is defined
    fail_msg: "缺少 node 构建必要的变量: {{ item }}"
    quiet: true
  loop:
    - NODE_VERSION
    - NODE_BUILD_CMD
    - BUILD_CODE_DIR
    - ARTIFACT_ROOT_DIR # 必须是这种 /data/artifact/test/app
    - PROJECT_PATH
    - USE_DOCKER
    - DOCKER_IMAGE_NODE

# 构建目录定义
- name: 定义 Node 产物目录
  set_fact:
    ARTIFACT_DIR: "{{ ARTIFACT_ROOT_DIR }}/{{ PROJECT_PATH }}"

# 打印开始信息
- name: 打印 Node 构建开始信息
  debug:
    msg:
      - "========================================"
      - "   Node 构建任务开始"
      - "========================================"
      - "Node 版本: {{ NODE_VERSION }}"
      - "源码目录: {{ BUILD_CODE_DIR }}"
      - "产物目录: {{ ARTIFACT_DIR }}"
      - "构建命令: {{ NODE_BUILD_CMD }}"

# 判断并执行构建
# A: 使用 Docker 构建
- name: Node 构建 (Docker 模式)
  block:
    - name: 确保 NPM 缓存目录存在
      file:
        path: "{{ ansible_env.HOME }}/.npm"
        state: directory  # 如果不存在，则创建
        mode: '0755'

    - name: 写入 npm 配置文件 (.npmrc)
      copy:
        dest: "{{ ansible_env.HOME }}/.npmrc"
        mode: '0755'
        content: |
          # 配置 npm 镜像源为 npmmirror
          registry=https://registry.npmmirror.com/
    - name: 运行 Docker 容器执行 Node 构建
      shell: |
        docker run --rm \
          -v "{{ BUILD_CODE_DIR }}:/app" \
          -v "{{ ansible_env.HOME }}/.npm:/root/.npm" \
          -v "{{ ansible_env.HOME }}/.npmrc:/root/.npmrc" \
          -w /app \
          {{ DOCKER_IMAGE_NODE }} \
          sh -c '{{ NODE_BUILD_CMD }}'

  when:
    - NODE_BUILD_CMD is defined
    - NODE_BUILD_CMD | length > 0
    - USE_DOCKER | bool

# B: 使用本机构建
- name: Node 构建
  block:
    - name: 执行 Native Node 构建
      command: "{{ NODE_BUILD_CMD }}"
      args:
        chdir: "{{ ARTIFACT_DIR }}"
  when:
    - NODE_BUILD_CMD is defined
    - NODE_BUILD_CMD | length > 0
    - not (USE_DOCKER | bool)

# 场景 C: 跳过构建
- name: 跳过构建 (未配置构建命令)
  debug:
    msg: "未配置 NODE_BUILD_CMD，跳过 Node 构建步骤。"
  when:
    - NODE_BUILD_CMD is not defined or NODE_BUILD_CMD | length == 0

# Rsync 同步源码到构建目录
- name: 确保 Node 产物目录存在
  file:
    path: "{{ ARTIFACT_DIR }}"
    state: directory
    mode: '0755'

- name: 同步源码到构建目录
  synchronize:
    src: "{{ BUILD_CODE_DIR }}/dist/"
    dest: "{{ ARTIFACT_DIR }}/"
    delete: yes
    rsync_opts:
      - "--chmod=755"
      - "--exclude=.git"
      - "--exclude=node_modules" # 排除源码中的 node_modules


# 打印完成信息
- name: 打印 Node 构建结束信息
  debug:
    msg:
      - "========================================"
      - "   Node 构建任务结束"
      - "========================================"
      - "产物目录: {{ ARTIFACT_DIR }}"
      - "构建状态: {{ '已执行构建' if (NODE_BUILD_CMD is defined and NODE_BUILD_CMD | length > 0) else '已跳过构建' }}"
