server {
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name h5.czwlinux.cloud;
    root /html/h5.czwlinux.cloud/;
    index index.html index.htm index.php;
    error_page 500 502 503 504 /50x.html;

    include conf.d/00-security.config;
    include conf.d/00-cors.config;
    # ssl config
    include conf.d/00-ssl.config;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # logs
    access_log  /var/log/nginx/h5.czwlinux.cloud_access.log  main;
    error_log /var/log/nginx/h5.czwlinux.cloud_error.log error;
}
