server {
    listen 443 ssl;                # 监听443端口, 开启ssl(必须)
    server_name www.czwlinux.cloud;
    root /html/;
    index index.html index.htm index.php;
    error_page 500 502 503 504 /50x.html;


    # ssl config
    # ssl_certificate      /etc/nginx/ssl/ssl.crt;
    # ssl_certificate_key  /etc/nginx/ssl/ssl_nokey.key;
    
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ecdh_curve X25519:prime256v1:secp384r1;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305;
    ssl_prefer_server_ciphers off;
    
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
    
    ssl_dhparam ssl/dhparam.pem;

    add_header Strict-Transport-Security "max-age=63072000" always;


    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # logs
    access_log  /var/log/nginx/h5.demo.czwlinux.cloud_access.log  main;
    error_log /var/log/nginx/h5.demo.czwlinux.cloud_error.log error;
}
