{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ds.name" . }}-api
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "api") | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ds.componentSelector" (dict "context" $ "component" "api") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: api-port
      path: /dolphinscheduler/actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ds.name" . }}-alert
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "alert") | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ds.componentSelector" (dict "context" $ "component" "alert") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: actuator-port
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ds.name" . }}-master
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "master") | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ds.componentSelector" (dict "context" $ "component" "master") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics-port
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ds.name" . }}-worker
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "worker") | nindent 4 }}
    {{- toYaml .Values.serviceMonitor.labels | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ds.componentSelector" (dict "context" $ "component" "worker") | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: metrics-port
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
