apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds.name" . }}-master-headless
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "master-headless") | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: 5678
      targetPort: master-port
      protocol: TCP
      name: master-port
    - port: 5679
      targetPort: metrics-port
      protocol: TCP
      name: metrics-port
  selector:
    {{- include "ds.componentSelector" (dict "context" $ "component" "master") | nindent 4 }}
