apiVersion: v1
kind: Service
metadata:
  name: {{ include "ds.name" . }}-api
  labels:
    {{- include "ds.componentLabels" (dict "context" $ "component" "api") | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: 12345
      targetPort: api-port
      {{- if and (eq .Values.api.service.type "NodePort") .Values.api.service.nodePort }}
      nodePort: {{ .Values.api.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: api-port
    - port: 25333
      targetPort: python-api-port
      protocol: TCP
      name: python-api-port
  selector:
    {{- include "ds.componentSelector" (dict "context" $ "component" "api") | nindent 4 }}
