
services:
  postgres15:
    image: postgres:15.5-alpine3.17
    container_name: postgres15
    #restart: always
    restart: unless-stopped
    environment:
      TZ: Aisa/Shanghai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    networks:
      - env-dev
    ports:
      - '5432:5432'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/lib/postgresql/data

networks:
  env-dev:
    external: true
