apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster-monitor
  namespace: redis-operator
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      redis_setup_type: cluster
  namespaceSelector:
    any: true
  endpoints:
  - port: redis-exporter
    interval: 15s
    path: /metrics
