apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: redis-kb
  namespace: redis
spec:
  terminationPolicy: Delete
  clusterDef: redis
  topology: replication
  componentSpecs:
    - name: redis
      serviceVersion: "7.2.7"
      disableExporter: false
      replicas: 3
      resources:
        limits:
          memory: 2Gi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: nfs-client
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
    - name: redis-sentinel
      serviceVersion: "7.2.7"
      replicas: 3
      resources:
        limits:
          memory: 512Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: nfs-client
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
