# site.yml
- name: Deploy application
  hosts: "{{ target_env }}"
  gather_facts: yes
  vars_files:
    - inventory/group_vars/all.yml

  roles:
    - role: git_pull
    # 按条件加载构建 Role
    - role: build_php
      when: PROJECT_TYPE == "php" | bool
    - role: build_node
      when: PROJECT_TYPE == "node" | bool
    - role: build_h5
      when: PROJECT_TYPE == "h5" | bool
    - role: deploy_push


# ansible-playbook site.yml \
#   -i inventory/hosts.ini \
#   -e target_env=testapp \
#   -e GIT_REPO="https://...git" \
#   -e GIT_BRANCH="main" \
#   -e PATH_MODE="project" \
#   -e php_build_enabled=true \
#   -e php_build_command="composer install --optimize-autoloader"