apiVersion: v2
name: dolphinscheduler
description: Apache DolphinScheduler - distributed workflow scheduler
home: https://dolphinscheduler.apache.org
icon: https://dolphinscheduler.apache.org/img/hlogo_colorful.svg
keywords:
  - dolphinscheduler
  - scheduler
  - workflow
type: application
version: 3.1.7
appVersion: 3.1.7
