{{- if .Values.standalone.enabled }}
---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: Redis
metadata:
  name: {{ .Values.standalone.name }}
spec:
  kubernetesConfig:
    image: "{{ $.Values.redisImage.repository }}:{{ $.Values.redisImage.tag }}"
    imagePullPolicy: {{ $.Values.redisImage.pullPolicy }}
    resources:
      requests:
        cpu: {{ .Values.standalone.resources.requests.cpu }}
        memory: {{ .Values.standalone.resources.requests.memory }}
      limits:
        memory: {{ .Values.standalone.resources.limits.memory }}
    {{- if .Values.standalone.redisSecret }}
    redisSecret:
      name: {{ .Values.standalone.redisSecret.name }}
      key: {{ .Values.standalone.redisSecret.key }}
    {{- end }}
  redisExporter:
    enabled: {{ .Values.standalone.exporter.enabled }}
    image: "{{ $.Values.redisExporterImage.repository }}:{{ $.Values.redisExporterImage.tag }}"
    imagePullPolicy: {{ $.Values.redisExporterImage.pullPolicy }}
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        memory: 128Mi
  storage:
    volumeClaimTemplate:
      spec:
        {{- if .Values.standalone.storageClassName }}
        storageClassName: {{ .Values.standalone.storageClassName }}
        {{- end }}
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.standalone.storage }}
  securityContext:
    runAsUser: {{ .Values.standalone.securityContext.runAsUser }}
    runAsGroup: {{ .Values.standalone.securityContext.runAsGroup }}
    fsGroup: {{ .Values.standalone.securityContext.fsGroup }}
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - {{ .Values.standalone.name }}
          topologyKey: kubernetes.io/hostname
{{- end }}
