apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{- include "redis-operator.labels" . | nindent 4 }}
  name: {{ include "redis-operator.name" . }}
  namespace: {{ include "redis-operator.namespace" . }}
