---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-operator
rules:
- apiGroups: [redis.redis.opstreelabs.in]
  resources: [rediss, redisclusters, redisreplications, redissentinels]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [redis.redis.opstreelabs.in]
  resources: [rediss/finalizers, redisclusters/finalizers, redisreplications/finalizers, redissentinels/finalizers]
  verbs: [update]
- apiGroups: [redis.redis.opstreelabs.in]
  resources: [rediss/status, redisclusters/status, redisreplications/status, redissentinels/status]
  verbs: [get, patch, update]
- apiGroups: [""]
  resources: [secrets, "pods/exec", services, configmaps, events, persistentvolumeclaims]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [apps]
  resources: [statefulsets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [policy]
  resources: [poddisruptionbudgets]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [autoscaling]
  resources: [horizontalpodautoscalers]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [coordination.k8s.io]
  resources: [leases]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [admissionregistration.k8s.io]
  resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
  verbs: [create, delete, get, list, patch, update, watch]
- apiGroups: [monitoring.coreos.com]
  resources: [servicemonitors, prometheusrules]
  verbs: [create, get, list, watch]
