# PostgreSQL 认证 Secret
# CNPG bootstrap 时会读取此 Secret 中的密码初始化用户
apiVersion: v1
kind: Secret
metadata:
  name: pg-auth-secret
  namespace: pg
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: pg@czw
