apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kdebug
  namespace: kdebug
  annotations:
    cert-manager.io/cluster-issuer: internal-ca
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kdebug.czw-sre.internal
      secretName: kdebug-tls
  rules:
    - host: kdebug.czw-sre.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kdebug
                port:
                  number: 80
