apiVersion: apps.kubeblocks.io/v1
kind: Cluster
metadata:
  name: valkey
  namespace: valkey
spec:
  terminationPolicy: Delete
  clusterDef: valkey
  topology: replication-8
  componentSpecs:
    - name: valkey
      serviceVersion: "8.1.8"
      disableExporter: false
      replicas: 2
      systemAccounts:
        - name: default
          secretRef:
            name: valkey-account
            namespace: valkey
      resources:
        limits:
          memory: 512Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
    - name: valkey-sentinel
      serviceVersion: "8.1.8"
      replicas: 3
      systemAccounts:
        - name: default
          secretRef:
            name: valkey-account
            namespace: valkey
      resources:
        limits:
          memory: 256Mi
      volumeClaimTemplates:
        - name: data
          spec:
            storageClassName: "nfs-client"
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Gi
