apiVersion: v1
kind: Service
metadata:
  name: demo-go-tiny-nodeport
  labels:
    app: demo-go-tiny
spec:
  type: NodePort
  selector:
    app: demo-go-tiny
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
