upstream backend-server-1 {
    server 192.168.1.213:32399;
    server 192.168.0.198:32399;
}

server {
    listen 80;
    listen [::]:80;
    listen 443 ssl;
    listen [::]:443 ssl;
    
    server_name api.czwlinux.cloud;
    index index.html index.htm index.php;
    error_page 500 502 503 504 /50x.html;
    
    include conf.d/00-security.config;
    include conf.d/00-cors.config;
    include conf.d/00-ssl.config;

    location / {
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
        proxy_pass http://backend-server-1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # logs
    access_log  /var/log/nginx/api.czwlinux.cloud_access.log  main;
    error_log /var/log/nginx/api.czwlinux.cloud_error.log error;
}
