services:
  phpfpm74:
    image: phpfpm:7.4
    container_name: phpfpm74
    restart: "always"
    environment:
      TZ: 'Asia/Shanghai'
    networks:
      - prodnet
    ports:
      - "9000:9000"
    working_dir: ${PROJECT_CODE_DIR}
    volumes:
      - ${PROJECT_CODE_DIR}:${PROJECT_CODE_DIR}:cached
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "9000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G

  phpfpm74-cron:
    image: phpfpm:7.4
    container_name: phpfpm74-cron
    environment:
      TZ: 'Asia/Shanghai'
    restart: "always"
    working_dir: /etc/cron.d/
    privileged: true
    volumes:
      - ${PROJECT_CODE_DIR}:${PROJECT_CODE_DIR}:cached
      - ${PROJECT_CRONTAB_DIR}:/etc/crontabs/
      - ${PROJECT_CRONTAB_LOG_DIR}:${PROJECT_CRONTAB_LOG_DIR}
    networks:
      - prodnet
    healthcheck:
      # 检测 crond 进程是否存在即可
      test: pidof crond
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    command: |
      sh -c "exec crond -f -l 2 -L /dev/stdout"

  phpfpm74-queue:
    image: phpfpm:7.4
    container_name: phpfpm74-queue
    environment:
      TZ: 'Asia/Shanghai'
    restart: "always"
    working_dir: /etc/supervisor/
    volumes:
      - ${PROJECT_CODE_DIR}:${PROJECT_CODE_DIR}:cached
      - ${PROJECT_SUPERVISOR_DIR}:/etc/supervisor/
      - ${PROJECT_SUPERVISOR_LOG_DIR}:${PROJECT_SUPERVISOR_LOG_DIR}
    networks:
      - prodnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 2G
    command: |
      sh -c "touch /var/log/supervisord.log &&
      exec supervisord -c /etc/supervisor/supervisord.conf"

networks:
  prodnet:
    external: true
