apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: sre-lab
  source:
    repoURL: 'https://github.com/jory-callan/sre-lab'
    targetRevision: main
    path: k8s/monitoring/helm
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
